const sampleUsers = [
  // 👨‍⚕️ Doctors (5)
  {
    name: "Dr. Amit Sharma",
    email: "amit.sharma@hospital.com",
    phone: "9000000001",
    password: "password123",
    role: "doctor",
  },
  {
    name: "Dr. Neha Verma",
    email: "neha.verma@hospital.com",
    phone: "9000000002",
    password: "password123",
    role: "doctor",
  },
  {
    name: "Dr. Rajesh Patil",
    email: "rajesh.patil@hospital.com",
    phone: "9000000003",
    password: "password123",
    role: "doctor",
  },
  {
    name: "Dr. Pooja Kulkarni",
    email: "pooja.kulkarni@hospital.com",
    phone: "9000000004",
    password: "password123",
    role: "doctor",
  },
  {
    name: "Dr. Sandeep Joshi",
    email: "sandeep.joshi@hospital.com",
    phone: "9000000005",
    password: "password123",
    role: "doctor",
  },

  // 🧑‍🤝‍🧑 Patients (20)
  {
    name: "Rahul Deshmukh",
    email: "rahul.d@gmail.com",
    phone: "9100000001",
    password: "password123",
    role: "patient",
  },
  {
    name: "Sneha Patil",
    email: "sneha.p@gmail.com",
    phone: "9100000002",
    password: "password123",
    role: "patient",
  },
  {
    name: "Amit Kale",
    email: "amit.k@gmail.com",
    phone: "9100000003",
    password: "password123",
    role: "patient",
  },
  {
    name: "Pooja Jadhav",
    email: "pooja.j@gmail.com",
    phone: "9100000004",
    password: "password123",
    role: "patient",
  },
  {
    name: "Rohit Patil",
    email: "rohit.p@gmail.com",
    phone: "9100000005",
    password: "password123",
    role: "patient",
  },
  {
    name: "Kavita More",
    email: "kavita.m@gmail.com",
    phone: "9100000006",
    password: "password123",
    role: "patient",
  },
  {
    name: "Sachin Pawar",
    email: "sachin.p@gmail.com",
    phone: "9100000007",
    password: "password123",
    role: "patient",
  },
  {
    name: "Anjali Kulkarni",
    email: "anjali.k@gmail.com",
    phone: "9100000008",
    password: "password123",
    role: "patient",
  },
  {
    name: "Nitin Shinde",
    email: "nitin.s@gmail.com",
    phone: "9100000009",
    password: "password123",
    role: "patient",
  },
  {
    name: "Priya Chavan",
    email: "priya.c@gmail.com",
    phone: "9100000010",
    password: "password123",
    role: "patient",
  },
  {
    name: "Akash Joshi",
    email: "akash.j@gmail.com",
    phone: "9100000011",
    password: "password123",
    role: "patient",
  },
  {
    name: "Meena Patankar",
    email: "meena.p@gmail.com",
    phone: "9100000012",
    password: "password123",
    role: "patient",
  },
  {
    name: "Vikas Gawande",
    email: "vikas.g@gmail.com",
    phone: "9100000013",
    password: "password123",
    role: "patient",
  },
  {
    name: "Komal Thakur",
    email: "komal.t@gmail.com",
    phone: "9100000014",
    password: "password123",
    role: "patient",
  },
  {
    name: "Suresh Bansod",
    email: "suresh.b@gmail.com",
    phone: "9100000015",
    password: "password123",
    role: "patient",
  },
  {
    name: "Rina Wankhede",
    email: "rina.w@gmail.com",
    phone: "9100000016",
    password: "password123",
    role: "patient",
  },
  {
    name: "Manoj Rathod",
    email: "manoj.r@gmail.com",
    phone: "9100000017",
    password: "password123",
    role: "patient",
  },
  {
    name: "Swati Desai",
    email: "swati.d@gmail.com",
    phone: "9100000018",
    password: "password123",
    role: "patient",
  },
  {
    name: "Deepak Suryawanshi",
    email: "deepak.s@gmail.com",
    phone: "9100000019",
    password: "password123",
    role: "patient",
  },
  {
    name: "Aarti Khot",
    email: "aarti.k@gmail.com",
    phone: "9100000020",
    password: "password123",
    role: "patient",
  },
];

module.exports = { data: sampleUsers };